# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-06 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('informal_name', models.TextField()),
                ('informal_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('informal_rank',),
            },
        ),
        migrations.CreateModel(
            name='FoodNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('cals_per_gram', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('fat_per_gram', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('carbs_per_gram', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('protein_per_gram', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('sugar_per_gram', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('food_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.FoodGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='meals.Foods')),
                ('main_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_food', to='meals.Foods')),
            ],
        ),
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='imperial', max_length=8)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.CharField(choices=[('none', ''), ('light', ''), ('medium', ''), ('high', ''), ('very high', '')], default='none', max_length=9)),
                ('direction', models.CharField(choices=[('lose', 'Lose'), ('maintain', 'Maintain'), ('gain', 'Gain')], default='lose', max_length=8)),
                ('change_rate', models.DecimalField(decimal_places=8, max_digits=9)),
                ('fat_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('protein_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=200)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='meals.Foods')),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='serving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Servings'),
        ),
        migrations.AddField(
            model_name='foods',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.FoodType'),
        ),
        migrations.AddField(
            model_name='foods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodnotes',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meals.Foods'),
        ),
    ]
