# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
