# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='direction',
            field=models.CharField(choices=[('lose', 'Lose'), ('maintain', 'Maintain'), ('gain', 'Gain')], default='lose', max_length=8),
        ),
        migrations.AlterField(
            model_name='macros',
            name='activity',
            field=models.IntegerField(choices=[('none', ''), ('light', ''), ('medium', ''), ('high', ''), ('very high', '')], default='none'),
        ),
    ]
