# Generated by Django 5.0.2 on 2024-05-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='sugar_per_gram',
        ),
    ]
