# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20181120_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='rank',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
