# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20171124_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='activity',
            field=models.CharField(choices=[('none', ''), ('light', ''), ('medium', ''), ('high', ''), ('very high', '')], default='none', max_length=9),
        ),
    ]
