# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20181120_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'ordering': ('informal_rank',)},
        ),
        migrations.RemoveField(
            model_name='foodgroup',
            name='rank',
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='informal_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
