# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20171124_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='macros',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='macros',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
