# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-22 17:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20181120_1644'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foods',
            managers=[
                ('searcher', django.db.models.manager.Manager()),
            ],
        ),
    ]
