# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_macros_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='unit_type',
            field=models.CharField(choices=[('i', 'Imperial'), ('m', 'Metric')], max_length=1),
        ),
    ]
