# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-22 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_auto_20181122_1703'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foods',
            managers=[
            ],
        ),
    ]
