# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20181122_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnotes',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meals.Foods'),
        ),
    ]
