# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20171209_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='unit_type',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='i', max_length=8),
        ),
    ]
