# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_auto_20171209_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealtemplate',
            old_name='daily_percent',
            new_name='cals',
        ),
        migrations.RemoveField(
            model_name='mealtemplate',
            name='num_per_day',
        ),
        migrations.AddField(
            model_name='mealtemplate',
            name='name',
            field=models.TextField(default='junk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='macros',
            name='unit_type',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='imperial', max_length=8),
        ),
    ]
