# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0011_auto_20171212_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtemplate',
            name='cals',
            field=models.IntegerField(),
        ),
    ]
