# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_mealtemplate_number_of_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='macros',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
