# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_auto_20171230_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtemplate',
            name='number_of_meals',
        ),
    ]
