# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_remove_mealtemplate_number_of_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='change_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
