# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_auto_20180104_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macros',
            name='change_rate',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
