# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_auto_20180104_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cals_per_gram', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fat_per_gram', models.DecimalField(decimal_places=4, max_digits=6)),
                ('carbs_per_gram', models.DecimalField(decimal_places=4, max_digits=6)),
                ('protein_per_gram', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
