pipeline:
    build:
        name: web
        image: python:3.6
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
            - ENV_DIR=/

        volumes:
            - /home/ubuntu:/

        commands:
            - pip install -r requirements.txt
            - python manage.py migrate
            - pytest meals
            # - export BROWSER=chrome
            # - pytest functional_tests
            # - export BROWSER=firefox
            # - pytest functional_tests
        when:
            branch: [ master ]
            event: [push, pull_request]

services:
    db:
        image: postgres
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        ports:
            - 5432:5432

    hub:
        image: selenium/hub:3.141.59
        ports:
            - 4444:4444

    chrome:
        image: selenium/node-chrome:3.141.59
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub

    firefox:
        image: selenium/node-firefox:3.141.59
        depends_on:
            - hub
        environment:
            - HUB_HOST=hub
