version: '3.6'

services:
    web:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
        entrypoint: ${DOCKER_ENTRYPOINT}
        volumes:
            - ${APP_DIR}:${DOCKER_APP_DIR}
            - ${APP_STATIC_DIR}:${DOCKER_APP_STATIC_DIR}
        env_file:
            - .env
        expose:
            - "8000"
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
        depends_on:
            - db
    db:
        image: postgres:10.1-alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
    nginx:
        build: ${APP_NGINX_DIR}
        volumes:
            - ${APP_STATIC_DIR}:${DOCKER_APP_STATIC_DIR}
        ports:
            - "${NGINX_PORT_MAP}"
        depends_on:
            - web
