version: '3.6'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn supermeals.wsgi:application --bind 0.0.0.0:8000 --reload
        volumes:
            - /srv/www/macrobatics/:/srv/www/app/
            - static_volume:/srv/www/macrobatics/static
        expose:
            - "8000"
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}

    nginx:
        build: /svr/www/macrobatics/nginx
        volumes:
            - static_volume:/svr/www/macrobatics/static
            - /svr/www/macrobatics/nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker-volumes/etc/letsencrypt/live/macrobatics-staging.xyz/fullchain.pem:/etc/letsencrypt/live/macrobatics-staging.xyz/fullchain.pem
            - /docker-volumes/etc/letsencrypt/live/macrobatics-staging.xyz/privkey.pem:/etc/letsencrypt/live/macrobatics-staging.xyz/privkey.pem
        ports:
            - "80:80"
            - "443:443"
        depends_on:

volumes:
	static_volume:
            - web
