version: '3.6'

services:
    db:
        image: postgres
    web:
        env_file:
            - .envs/.dev/.postgres
            - .envs/.dev/.django
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${APP_DIR}:${DOCKER_APP_DIR}
            - ${APP_STATIC_DIR}:${DOCKER_APP_STATIC_DIR}
        expose:
            - 8000
        depends_on:
            - db
    nginx:
        build: ${APP_NGINX_DIR}
        volumes:
            - ${APP_STATIC_DIR}:${DOCKER_APP_STATIC_DIR}
            - ${DH_PARAM_PATH}:${DH_PARAM_DOCKER_PATH}
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web
